

export class GeneratedImages {
    public id:string;
    public files:Array<any>;
    public title:string;
    public description:string;
    private active:boolean=false;

    constructor(id:string,title:string,description:string, files:Array<any>)
        { 

                this.id=id;
                this.title=title;
                this.files=files;
                this.description=description;
                




                  }
            public isActive(){

                return this.active;

            }

            public setActive(active:boolean=true){
                this.active=active;
            }




}


export const DefaultInputValues={
    "armslegs/l-lowerarm-fat-decr|incr":0.0,
    "armslegs/l-lowerarm-muscle-decr|incr":0.0,
    "armslegs/l-lowerarm-scale-depth-decr|incr":0.0,
    "armslegs/l-lowerarm-scale-horiz-decr|incr":0.0,
    "armslegs/l-lowerarm-scale-vert-decr|incr":0.0,
    "armslegs/l-upperarm-fat-decr|incr":0.0,
    "armslegs/l-upperarm-muscle-decr|incr":0.0,
    "armslegs/l-upperarm-scale-depth-decr|incr":0.0,
    "armslegs/l-upperarm-scale-horiz-decr|incr":0.0,
    "armslegs/l-upperarm-scale-vert-decr|incr":0.0,
    "armslegs/l-upperarm-shoulder-muscle-decr|incr":0.0,
    "armslegs/r-lowerarm-fat-decr|incr":0.0,
    "armslegs/r-lowerarm-muscle-decr|incr":0.0,
    "armslegs/r-lowerarm-scale-depth-decr|incr":0.0,
    "armslegs/r-lowerarm-scale-horiz-decr|incr":0.0,
    "armslegs/r-lowerarm-scale-vert-decr|incr":0.0,
    "armslegs/r-upperarm-fat-decr|incr":0.0,
    "armslegs/r-upperarm-muscle-decr|incr":0.0,
    "armslegs/r-upperarm-scale-depth-decr|incr":0.0,
    "armslegs/r-upperarm-scale-horiz-decr|incr":0.0,
    "armslegs/r-upperarm-scale-vert-decr|incr":0.0,
    "armslegs/r-upperarm-shoulder-muscle-decr|incr":0.0,
    "measure/measure-lowerarm-length-decr|incr":0.0,
"measure/measure-shoulder-dist-decr|incr":0.0,
"measure/measure-upperarm-circ-decr|incr":0.0,
"measure/measure-upperarm-length-decr|incr":0.0,
"breast/BreastFirmness":0.5,
"breast/BreastSize":0.5,
"breast/breast-dist-decr|incr":0.0,
"breast/breast-point-decr|incr":0.0,
"breast/breast-trans-down|up":0.0,
"breast/breast-volume-vert-down|up":0.0,
"breast/nipple-point-decr|incr":0.0,
"breast/nipple-size-decr|incr":0.0,
"measure/measure-bust-circ-decr|incr":0.0,
"measure/measure-underbust-circ-decr|incr":0.0,
"cheek/l-cheek-bones-decr|incr":0.0,
"cheek/l-cheek-inner-decr|incr":0.0,
"cheek/l-cheek-trans-down|up":0.0,
"cheek/l-cheek-volume-decr|incr":0.0,
"cheek/r-cheek-bones-decr|incr":0.0,
"cheek/r-cheek-inner-decr|incr":0.0,
"cheek/r-cheek-trans-down|up":0.0,
"cheek/r-cheek-volume-decr|incr":0.0,
"chin/chin-bones-decr|incr":0.0,
"chin/chin-cleft-decr|incr":0.0,
"chin/chin-height-decr|incr":0.0,
"chin/chin-jaw-drop-decr|incr":0.0,
"chin/chin-prognathism-decr|incr":0.0,
"chin/chin-prominent-decr|incr":0.0,
"chin/chin-width-decr|incr":0.0,
"ears/l-ear-flap-decr|incr":0.0,
"ears/l-ear-lobe-decr|incr":0.0,
"ears/l-ear-rot-backward|forward":0.0,
"ears/l-ear-scale-decr|incr":0.0,
"ears/l-ear-scale-depth-decr|incr":0.0,
"ears/l-ear-scale-vert-decr|incr":0.0,
"ears/l-ear-shape-pointed|triangle":0.0,
"ears/l-ear-shape-square|round":0.0,
"ears/l-ear-trans-backward|forward":0.0,
"ears/l-ear-trans-down|up":0.0,
"ears/l-ear-wing-decr|incr":0.0,
"ears/r-ear-flap-decr|incr":0.0,
"ears/r-ear-lobe-decr|incr":0.0,
"ears/r-ear-rot-backward|forward":0.0,
"ears/r-ear-scale-decr|incr":0.0,
"ears/r-ear-scale-depth-decr|incr":0.0,
"ears/r-ear-scale-vert-decr|incr":0.0,
"ears/r-ear-shape-pointed|triangle":0.0,
"ears/r-ear-shape-square|round":0.0,
"ears/r-ear-trans-backward|forward":0.0,
"ears/r-ear-trans-down|up":0.0,
"ears/r-ear-wing-decr|incr":0.0,
"eyes/l-eye-bag-decr|incr":0.0,
"eyes/l-eye-bag-height-decr|incr":0.0,
"eyes/l-eye-bag-in|out":0.0,
"eyes/l-eye-corner1-down|up":0.0,
"eyes/l-eye-corner2-down|up":0.0,
"eyes/l-eye-epicanthus-in|out":0.0,
"eyes/l-eye-eyefold-angle-down|up":0.0,
"eyes/l-eye-eyefold-concave|convex":0.0,
"eyes/l-eye-eyefold-down|up":0.0,
"eyes/l-eye-height1-decr|incr":0.0,
"eyes/l-eye-height2-decr|incr":0.0,
"eyes/l-eye-height3-decr|incr":0.0,
"eyes/l-eye-push1-in|out":0.0,
"eyes/l-eye-push2-in|out":0.0,
"eyes/l-eye-scale-decr|incr":0.0,
"eyes/l-eye-trans-down|up":0.0,
"eyes/l-eye-trans-in|out":0.0,
"eyes/r-eye-bag-decr|incr":0.0,
"eyes/r-eye-bag-height-decr|incr":0.0,
"eyes/r-eye-bag-in|out":0.0,
"eyes/r-eye-corner1-down|up":0.0,
"eyes/r-eye-corner2-down|up":0.0,
"eyes/r-eye-epicanthus-in|out":0.0,
"eyes/r-eye-eyefold-angle-down|up":0.0,
"eyes/r-eye-eyefold-concave|convex":0.0,
"eyes/r-eye-eyefold-down|up":0.0,
"eyes/r-eye-height1-decr|incr":0.0,
"eyes/r-eye-height2-decr|incr":0.0,
"eyes/r-eye-height3-decr|incr":0.0,
"eyes/r-eye-push1-in|out":0.0,
"eyes/r-eye-push2-in|out":0.0,
"eyes/r-eye-scale-decr|incr":0.0,
"eyes/r-eye-trans-down|up":0.0,
"eyes/r-eye-trans-in|out":0.0,
"armslegs/r-foot-scale-decr|incr":0.0,
"armslegs/r-foot-trans-backward|forward":0.0,
"armslegs/r-foot-trans-in|out":0.0,
"measure/measure-ankle-circ-decr|incr":0.0,
"armslegs/l-hand-fingers-diameter-decr|incr":0.0,
"armslegs/l-hand-fingers-distance-decr|incr":0.0,
"armslegs/l-hand-fingers-length-decr|incr":0.0,
"armslegs/l-hand-scale-decr|incr":0.0,
"armslegs/l-hand-trans-in|out":0.0,
"armslegs/r-hand-fingers-diameter-decr|incr":0.0,
"armslegs/r-hand-fingers-distance-decr|incr":0.0,
"armslegs/r-hand-fingers-length-decr|incr":0.0,
"armslegs/r-hand-scale-decr|incr":0.0,
"armslegs/r-hand-trans-in|out":0.0,
"measure/measure-wrist-circ-decr|incr":0.0,
"forehead/forehead-nubian-decr|incr":0.0,
"forehead/forehead-scale-vert-decr|incr":0.0,
"forehead/forehead-temple-decr|incr":0.0,
"forehead/forehead-trans-backward|forward":0.0,
"head/head-age-decr|incr":0.0,
"head/head-angle-in|out":0.0,
"head/head-back-scale-depth-decr|incr":0.0,
"head/head-diamond":0.0,
"head/head-fat-decr|incr":0.0,
"head/head-invertedtriangular":0.0,
"head/head-oval":0.0,
"head/head-rectangular":0.0,
"head/head-round":0.0,
"head/head-scale-depth-decr|incr":0.0,
"head/head-scale-horiz-decr|incr":0.0,
"head/head-scale-vert-decr|incr":0.0,
"head/head-square":0.0,
"head/head-trans-backward|forward":0.0,
"head/head-trans-down|up":0.0,
"head/head-trans-in|out":0.0,
"head/head-triangular":0.0,
"armslegs/l-foot-scale-decr|incr":0.0,
"armslegs/l-foot-trans-backward|forward":0.0,
"armslegs/l-foot-trans-in|out":0.0,
"armslegs/l-leg-valgus-decr|incr":0.0,
"armslegs/l-lowerleg-fat-decr|incr":0.0,
"armslegs/l-lowerleg-muscle-decr|incr":0.0,
"armslegs/l-lowerleg-scale-depth-decr|incr":0.0,
"armslegs/l-lowerleg-scale-horiz-decr|incr":0.0,
"armslegs/l-upperleg-fat-decr|incr":0.0,
"armslegs/l-upperleg-muscle-decr|incr":0.0,
"armslegs/l-upperleg-scale-depth-decr|incr":0.0,
"armslegs/l-upperleg-scale-horiz-decr|incr":0.0,
"armslegs/l-upperleg-scale-vert-decr|incr":0.0,
"armslegs/lowerlegs-height-decr|incr":0.0,
"armslegs/r-leg-valgus-decr|incr":0.0,
"armslegs/r-lowerleg-fat-decr|incr":0.0,
"armslegs/r-lowerleg-muscle-decr|incr":0.0,
"armslegs/r-lowerleg-scale-depth-decr|incr":0.0,
"armslegs/r-lowerleg-scale-horiz-decr|incr":0.0,
"armslegs/r-upperleg-fat-decr|incr":0.0,
"armslegs/r-upperleg-muscle-decr|incr":0.0,
"armslegs/r-upperleg-scale-depth-decr|incr":0.0,
"armslegs/r-upperleg-scale-horiz-decr|incr":0.0,
"armslegs/r-upperleg-scale-vert-decr|incr":0.0,
"armslegs/upperlegs-height-decr|incr":0.0,
"measure/measure-calf-circ-decr|incr":0.0,
"measure/measure-hips-circ-decr|incr":0.0,
"measure/measure-knee-circ-decr|incr":0.0,
"measure/measure-lowerleg-height-decr|incr":0.0,
"measure/measure-thigh-circ-decr|incr":0.0,
"measure/measure-upperleg-height-decr|incr":0.0,
"mouth/mouth-angles-down|up":0.0,
"mouth/mouth-cupidsbow-decr|incr":0.0,
"mouth/mouth-cupidsbow-width-decr|incr":0.0,
"mouth/mouth-dimples-in|out":0.0,
"mouth/mouth-laugh-lines-in|out":0.0,
"mouth/mouth-lowerlip-ext-down|up":0.0,
"mouth/mouth-lowerlip-height-decr|incr":0.0,
"mouth/mouth-lowerlip-middle-down|up":0.0,
"mouth/mouth-lowerlip-volume-decr|incr":0.0,
"mouth/mouth-lowerlip-width-decr|incr":0.0,
"mouth/mouth-philtrum-volume-decr|incr":0.0,
"mouth/mouth-scale-depth-decr|incr":0.0,
"mouth/mouth-scale-horiz-decr|incr":0.0,
"mouth/mouth-scale-vert-decr|incr":0.0,
"mouth/mouth-trans-backward|forward":0.0,
"mouth/mouth-trans-down|up":0.0,
"mouth/mouth-trans-in|out":0.0,
"mouth/mouth-upperlip-ext-down|up":0.0,
"mouth/mouth-upperlip-height-decr|incr":0.0,
"mouth/mouth-upperlip-middle-down|up":0.0,
"mouth/mouth-upperlip-volume-decr|incr":0.0,
"mouth/mouth-upperlip-width-decr|incr":0.0,
"neck/neck-back-scale-depth-decr|incr":0.0,
"neck/neck-double-decr|incr":0.0,
"neck/neck-scale-depth-decr|incr":0.0,
"neck/neck-scale-horiz-decr|incr":0.0,
"neck/neck-scale-vert-decr|incr":0.0,
"neck/neck-trans-backward|forward":0.0,
"neck/neck-trans-down|up":0.0,
"neck/neck-trans-in|out":0.0,
"measure/measure-neck-circ-decr|incr":0.0,
"measure/measure-neck-height-decr|incr":0.0,
"nose/nose-base-down|up":0.0,
"nose/nose-compression-compress|uncompress":0.0,
"nose/nose-curve-concave|convex":0.0,
"nose/nose-flaring-decr|incr":0.0,
"nose/nose-greek-decr|incr":0.0,
"nose/nose-hump-decr|incr":0.0,
"nose/nose-nostrils-angle-down|up":0.0,
"nose/nose-nostrils-width-decr|incr":0.0,
"nose/nose-point-down|up":0.0,
"nose/nose-point-width-decr|incr":0.0,
"nose/nose-scale-depth-decr|incr":0.0,
"nose/nose-scale-horiz-decr|incr":0.0,
"nose/nose-scale-vert-decr|incr":0.0,
"nose/nose-septumangle-decr|incr":0.0,
"nose/nose-trans-backward|forward":0.0,
"nose/nose-trans-down|up":0.0,
"nose/nose-trans-in|out":0.0,
"nose/nose-volume-decr|incr":0.0,
"nose/nose-width1-decr|incr":0.0,
"nose/nose-width2-decr|incr":0.0,
"nose/nose-width3-decr|incr":0.0,
"stomach/stomach-navel-down|up":0.0,
"stomach/stomach-navel-in|out":0.0,
"stomach/stomach-pregnant-decr|incr":0.0,
"stomach/stomach-tone-decr|incr":0.0,
"torso/torso-muscle-dorsi-decr|incr":0.0,
"torso/torso-muscle-pectoral-decr|incr":0.0,
"torso/torso-scale-depth-decr|incr":0.0,
"torso/torso-scale-horiz-decr|incr":0.0,
"torso/torso-scale-vert-decr|incr":0.0,
"torso/torso-trans-backward|forward":0.0,
"torso/torso-trans-down|up":0.0,
"torso/torso-trans-in|out":0.0,
"torso/torso-vshape-decr|incr":0.0,
"measure/measure-frontchest-dist-decr|incr":0.0,
"measure/measure-napetowaist-dist-decr|incr":0.0,
"measure/measure-waist-circ-decr|incr":0.0,
"measure/measure-waisttohip-dist-decr|incr":0.0,
}



